service: intcodeComputer

provider:
  name: aws
  runtime: python3.8
  stage: dev
  region: eu-north-1
  websocketsApiName: intcode-computer-websockets
  websocketsApiRouteSelectionExpression: $request.body.action

functions:
  connectHandler:
    handler: handler.connect_handler
    events:
      - websocket: $connect
  disconnectHandler:
    handler: handler.disconnect_handler
    events:
      - websocket: $disconnect
  defaultHandler:
    handler: handler.default_handler
    events:
      - websocket: $default