service: intcodeComputer

custom:
  tableName: 'intcode-computer-${self:provider.stage}'

provider:
  name: aws
  runtime: python3.8
  region: eu-north-1
  memorySize: 128
  websocketsApiName: intcode-computer-websockets
  websocketsApiRouteSelectionExpression: $request.body.action
  iamRoleStatements:
    - Effect: Allow
      Action:
        - dynamodb:Query
        - dynamodb:Scan
        - dynamodb:GetItem
        - dynamodb:PutItem
        - dynamodb:UpdateItem
        - dynamodb:DeleteItem
      Resource:
        - { "Fn::GetAtt": ["IntcodeComputerDynamoDBTable", "Arn" ] }
  environment:
    INTCODE_TABLE: ${self:custom.tableName}

functions:
  connectHandler:
    handler: handler.connect_handler
    events:
      - websocket: $connect
  disconnectHandler:
    handler: handler.disconnect_handler
    events:
      - websocket: $disconnect
  defaultHandler:
    handler: handler.default_handler
    events:
      - websocket: $default
  additionalInputHandler:
    handler: handler.additional_input_handler
    events:
      - websocket:
          route: additional_input

resources:
  Resources:
    IntcodeComputerDynamoDBTable:
      Type: 'AWS::DynamoDB::Table'
      Properties:
        AttributeDefinitions:
          -
            AttributeName: ConnectionId
            AttributeType: S
        KeySchema:
          -
            AttributeName: ConnectionId
            KeyType: HASH
        ProvisionedThroughput:
          ReadCapacityUnits: 3
          WriteCapacityUnits: 3
        TableName: ${self:custom.tableName}